pars_data = {0: {'title': 'Генерирующие агрегаты', 'subcategory': {'Sähkögeneraattori': {'ADLER': {
    '3800.288': {'quantity': '--', 'price': '450,96',
                 'image': 'C:\\Users\\user\\PycharmProjects\\intercars\\data\\0\\ADLER\\3800288\\logo.jpg',
                 'kriterii': {'Käynnistinmoottori teho (kW)': '2,5 kW', 'Jännite ulos [V]': '230 V'},
                 'alternative': ['3700.1', '3800.288', '3800.588', '3800.688', 'KS 3000', 'KS 7000E ATS', 'KS 10000E',
                                 'EA3000N2 AVR', 'KS10000E3', 'KS3000E', 'EP13500TE', 'FH8000', 'SE2000IE', 'EA300N1',
                                 'FV13000TRE', 'KS9200HDES1-3-ATSR', 'KS8100HDE', 'KS12-1E ATSR', 'BARRACUDA9000-3F',
                                 'BARRACUDA5500-1F', 'KD122', 'SE4500IE', 'KS10000E-3', 'S-THOR50IG', 'ZBG3300C',
                                 'KS10000EG', 'S-THOR10', 'S-THOR10ATS', 'S-THOR7', 'F3001R', 'ZBG10003CEA',
                                 '1.042-209.0'], 'more': '', 'name': 'AGREGAT AD-288S 230V'},
    '3700.1': {'quantity': '--', 'price': '493,39',
               'image': 'C:\\Users\\user\\PycharmProjects\\intercars\\data\\0\\ADLER\\37001\\logo.jpg',
               'kriterii': {'Käynnistinmoottori teho (kW)': '1,2 kW', 'Jännite ulos [V]': '230 V'},
               'alternative': ['3700.1', '3800.288', '3800.588', '3800.688', 'KS 3000', 'KS 7000E ATS', 'KS 10000E',
                               'EA3000N2 AVR', 'KS10000E3', 'KS3000E', 'EP13500TE', 'FH8000', 'SE2000IE', 'EA300N1',
                               'FV13000TRE', 'KS9200HDES1-3-ATSR', 'KS8100HDE', 'KS12-1E ATSR', 'BARRACUDA9000-3F',
                               'BARRACUDA5500-1F', 'KD122', 'SE4500IE', 'KS10000E-3', 'S-THOR50IG', 'ZBG3300C',
                               'KS10000EG', 'S-THOR10', 'S-THOR10ATS', 'S-THOR7', 'F3001R', 'ZBG10003CEA',
                               '1.042-209.0'], 'more': '', 'name': 'AGREGAT AD-1500 ADLER'},
    '3800.588': {'quantity': '--', 'price': '943,20',
                 'image': 'C:\\Users\\user\\PycharmProjects\\intercars\\data\\0\\ADLER\\3800588\\logo.jpg',
                 'kriterii': {'Käynnistinmoottori teho (kW)': '5 kW', 'Jännite ulos [V]': '230 V'},
                 'alternative': ['3700.1', '3800.288', '3800.588', '3800.688', 'KS 3000', 'KS 7000E ATS', 'KS 10000E',
                                 'EA3000N2 AVR', 'KS10000E3', 'KS3000E', 'EP13500TE', 'FH8000', 'SE2000IE', 'EA300N1',
                                 'FV13000TRE', 'KS9200HDES1-3-ATSR', 'KS8100HDE', 'KS12-1E ATSR', 'BARRACUDA9000-3F',
                                 'BARRACUDA5500-1F', 'KD122', 'SE4500IE', 'KS10000E-3', 'S-THOR50IG', 'ZBG3300C',
                                 'KS10000EG', 'S-THOR10', 'S-THOR10ATS', 'S-THOR7', 'F3001R', 'ZBG10003CEA',
                                 '1.042-209.0'], 'more': '', 'name': 'AGREGAT AD-588S 230V'},
    '3800.688': {'quantity': '--', 'price': '1000,86',
                 'image': 'C:\\Users\\user\\PycharmProjects\\intercars\\data\\0\\ADLER\\3800688\\logo.jpg',
                 'kriterii': {'Käynnistinmoottori teho (kW)': '6,2 kW', 'Jännite ulos [V]': '400 V'},
                 'alternative': ['3700.1', '3800.288', '3800.588', '3800.688', 'KS 3000', 'KS 7000E ATS', 'KS 10000E',
                                 'EA3000N2 AVR', 'KS10000E3', 'KS3000E', 'EP13500TE', 'FH8000', 'SE2000IE', 'EA300N1',
                                 'FV13000TRE', 'KS9200HDES1-3-ATSR', 'KS8100HDE', 'KS12-1E ATSR', 'BARRACUDA9000-3F',
                                 'BARRACUDA5500-1F', 'KD122', 'SE4500IE', 'KS10000E-3', 'S-THOR50IG', 'ZBG3300C',
                                 'KS10000EG', 'S-THOR10', 'S-THOR10ATS', 'S-THOR7', 'F3001R', 'ZBG10003CEA',
                                 '1.042-209.0'], 'more': '', 'name': 'AGREGAT PRADOTWÓRCZY AD-688S 230V/400V'},
    '3800.689-1': {'quantity': '--', 'price': '874,96', 'image': '', 'kriterii': {}, 'alternative': [], 'more': '',
                   'name': 'AGREGAT PRADOTWÓRCZY 6,2 KW, 230/400V'}}, 'DeWalt': {
    'KS10000E-3': {'quantity': '--', 'price': '1290,36',
                   'image': 'C:\\Users\\user\\PycharmProjects\\intercars\\data\\0\\DeWalt\\KS10000E3\\logo.jpg',
                   'kriterii': {},
                   'alternative': ['3700.1', '3800.288', '3800.588', '3800.688', 'KS 3000', 'KS 7000E ATS', 'KS 10000E',
                                   'EA3000N2 AVR', 'KS10000E3', 'KS3000E', 'EP13500TE', 'FH8000', 'SE2000IE', 'EA300N1',
                                   'FV13000TRE', 'KS9200HDES1-3-ATSR', 'KS8100HDE', 'KS12-1E ATSR', 'BARRACUDA9000-3F',
                                   'BARRACUDA5500-1F', 'KD122', 'SE4500IE', 'KS10000E-3', 'S-THOR50IG', 'ZBG3300C',
                                   'KS10000EG', 'S-THOR10', 'S-THOR10ATS', 'S-THOR7', 'F3001R', 'ZBG10003CEA',
                                   '1.042-209.0'], 'more': '',
                   'name': 'AGREGAT PRADOTWÓRCZY 8KW, 400V, BENZYNA, ATS, AVR'},
    'EA300N1': {'quantity': '--', 'price': '578,54', 'image': '', 'kriterii': {},
                'alternative': ['3700.1', '3800.288', '3800.588', '3800.688', 'KS 3000', 'KS 7000E ATS', 'KS 10000E',
                                'EA3000N2 AVR', 'KS10000E3', 'KS3000E', 'EP13500TE', 'FH8000', 'SE2000IE', 'EA300N1',
                                'FV13000TRE', 'KS9200HDES1-3-ATSR', 'KS8100HDE', 'KS12-1E ATSR', 'BARRACUDA9000-3F',
                                'BARRACUDA5500-1F', 'KD122', 'SE4500IE', 'KS10000E-3', 'S-THOR50IG', 'ZBG3300C',
                                'KS10000EG', 'S-THOR10', 'S-THOR10ATS', 'S-THOR7', 'F3001R', 'ZBG10003CEA',
                                '1.042-209.0'], 'more': '', 'name': 'AGREGAT HONDA EA300N1'},
    'KS10000EG': {'quantity': '--', 'price': '1440,40',
                  'image': 'C:\\Users\\user\\PycharmProjects\\intercars\\data\\0\\DeWalt\\KS10000EG\\logo.jpg',
                  'kriterii': {},
                  'alternative': ['3700.1', '3800.288', '3800.588', '3800.688', 'KS 3000', 'KS 7000E ATS', 'KS 10000E',
                                  'EA3000N2 AVR', 'KS10000E3', 'KS3000E', 'EP13500TE', 'FH8000', 'SE2000IE', 'EA300N1',
                                  'FV13000TRE', 'KS9200HDES1-3-ATSR', 'KS8100HDE', 'KS12-1E ATSR', 'BARRACUDA9000-3F',
                                  'BARRACUDA5500-1F', 'KD122', 'SE4500IE', 'KS10000E-3', 'S-THOR50IG', 'ZBG3300C',
                                  'KS10000EG', 'S-THOR10', 'S-THOR10ATS', 'S-THOR7', 'F3001R', 'ZBG10003CEA',
                                  '1.042-209.0'], 'more': '',
                  'name': 'AGREGAT PRADOTWÓRCZY 8KW, 230V, BENZYNA+LPG, AVR'},
    'KS12-1E ATSR': {'quantity': '--', 'price': '1800,50',
                     'image': 'C:\\Users\\user\\PycharmProjects\\intercars\\data\\0\\DeWalt\\KS121E ATSR\\logo.jpg',
                     'kriterii': {},
                     'alternative': ['3700.1', '3800.288', '3800.588', '3800.688', 'KS 3000', 'KS 7000E ATS',
                                     'KS 10000E', 'EA3000N2 AVR', 'KS10000E3', 'KS3000E', 'EP13500TE', 'FH8000',
                                     'SE2000IE', 'EA300N1', 'FV13000TRE', 'KS9200HDES1-3-ATSR', 'KS8100HDE',
                                     'KS12-1E ATSR', 'BARRACUDA9000-3F', 'BARRACUDA5500-1F', 'KD122', 'SE4500IE',
                                     'KS10000E-3', 'S-THOR50IG', 'ZBG3300C', 'KS10000EG', 'S-THOR10', 'S-THOR10ATS',
                                     'S-THOR7', 'F3001R', 'ZBG10003CEA', '1.042-209.0'], 'more': '',
                     'name': 'AGREGAT PRADOTWÓRCZY KS12-1E ATSR 9KW, 230V, BENZYNA'},
    'SE4500IE': {'quantity': '--', 'price': '1129,37', 'image': '', 'kriterii': {},
                 'alternative': ['3700.1', '3800.288', '3800.588', '3800.688', 'KS 3000', 'KS 7000E ATS', 'KS 10000E',
                                 'EA3000N2 AVR', 'KS10000E3', 'KS3000E', 'EP13500TE', 'FH8000', 'SE2000IE', 'EA300N1',
                                 'FV13000TRE', 'KS9200HDES1-3-ATSR', 'KS8100HDE', 'KS12-1E ATSR', 'BARRACUDA9000-3F',
                                 'BARRACUDA5500-1F', 'KD122', 'SE4500IE', 'KS10000E-3', 'S-THOR50IG', 'ZBG3300C',
                                 'KS10000EG', 'S-THOR10', 'S-THOR10ATS', 'S-THOR7', 'F3001R', 'ZBG10003CEA',
                                 '1.042-209.0'], 'more': '', 'name': 'INWERTOROWY AGREGAT PRADOTWÓRCZY SE2000IE'}},
                                                                                         'Diagnostic': {
                                                                                             'BARRACUDA5500-1F': {
                                                                                                 'quantity': '--',
                                                                                                 'price': '1101,52',
                                                                                                 'image': '',
                                                                                                 'kriterii': {},
                                                                                                 'alternative': [
                                                                                                     '3700.1',
                                                                                                     '3800.288',
                                                                                                     '3800.588',
                                                                                                     '3800.688',
                                                                                                     'KS 3000',
                                                                                                     'KS 7000E ATS',
                                                                                                     'KS 10000E',
                                                                                                     'EA3000N2 AVR',
                                                                                                     'KS10000E3',
                                                                                                     'KS3000E',
                                                                                                     'EP13500TE',
                                                                                                     'FH8000',
                                                                                                     'SE2000IE',
                                                                                                     'EA300N1',
                                                                                                     'FV13000TRE',
                                                                                                     'KS9200HDES1-3-ATSR',
                                                                                                     'KS8100HDE',
                                                                                                     'KS12-1E ATSR',
                                                                                                     'BARRACUDA9000-3F',
                                                                                                     'BARRACUDA5500-1F',
                                                                                                     'KD122',
                                                                                                     'SE4500IE',
                                                                                                     'KS10000E-3',
                                                                                                     'S-THOR50IG',
                                                                                                     'ZBG3300C',
                                                                                                     'KS10000EG',
                                                                                                     'S-THOR10',
                                                                                                     'S-THOR10ATS',
                                                                                                     'S-THOR7',
                                                                                                     'F3001R',
                                                                                                     'ZBG10003CEA',
                                                                                                     '1.042-209.0'],
                                                                                                 'more': '',
                                                                                                 'name': 'AGREGAT PRADOTWÓRCZY 7 KVA 1F BARRACUDA 5500 Z ROZRUCHEM ELE'},
                                                                                             'BARRACUDA9000-3F': {
                                                                                                 'quantity': '--',
                                                                                                 'price': '1753,89',
                                                                                                 'image': '',
                                                                                                 'kriterii': {},
                                                                                                 'alternative': [
                                                                                                     '3700.1',
                                                                                                     '3800.288',
                                                                                                     '3800.588',
                                                                                                     '3800.688',
                                                                                                     'KS 3000',
                                                                                                     'KS 7000E ATS',
                                                                                                     'KS 10000E',
                                                                                                     'EA3000N2 AVR',
                                                                                                     'KS10000E3',
                                                                                                     'KS3000E',
                                                                                                     'EP13500TE',
                                                                                                     'FH8000',
                                                                                                     'SE2000IE',
                                                                                                     'EA300N1',
                                                                                                     'FV13000TRE',
                                                                                                     'KS9200HDES1-3-ATSR',
                                                                                                     'KS8100HDE',
                                                                                                     'KS12-1E ATSR',
                                                                                                     'BARRACUDA9000-3F',
                                                                                                     'BARRACUDA5500-1F',
                                                                                                     'KD122',
                                                                                                     'SE4500IE',
                                                                                                     'KS10000E-3',
                                                                                                     'S-THOR50IG',
                                                                                                     'ZBG3300C',
                                                                                                     'KS10000EG',
                                                                                                     'S-THOR10',
                                                                                                     'S-THOR10ATS',
                                                                                                     'S-THOR7',
                                                                                                     'F3001R',
                                                                                                     'ZBG10003CEA',
                                                                                                     '1.042-209.0'],
                                                                                                 'more': '',
                                                                                                 'name': 'AGREGAT PRADOTWÓRCZY 11KVA 3F BARRACUDA 9000 Z ROZRUCHEM ELE'},
                                                                                             'FH9000TRE': {
                                                                                                 'quantity': '--',
                                                                                                 'price': '2254,40',
                                                                                                 'image': '',
                                                                                                 'kriterii': {},
                                                                                                 'alternative': [],
                                                                                                 'more': '',
                                                                                                 'name': 'AGREGAT PRADOTWÓRCZY FOGO FH 9000TRE'},
                                                                                             'F3001R': {
                                                                                                 'quantity': '--',
                                                                                                 'price': '698,98',
                                                                                                 'image': '',
                                                                                                 'kriterii': {},
                                                                                                 'alternative': [
                                                                                                     '3700.1',
                                                                                                     '3800.288',
                                                                                                     '3800.588',
                                                                                                     '3800.688',
                                                                                                     'KS 3000',
                                                                                                     'KS 7000E ATS',
                                                                                                     'KS 10000E',
                                                                                                     'EA3000N2 AVR',
                                                                                                     'KS10000E3',
                                                                                                     'KS3000E',
                                                                                                     'EP13500TE',
                                                                                                     'FH8000',
                                                                                                     'SE2000IE',
                                                                                                     'EA300N1',
                                                                                                     'FV13000TRE',
                                                                                                     'KS9200HDES1-3-ATSR',
                                                                                                     'KS8100HDE',
                                                                                                     'KS12-1E ATSR',
                                                                                                     'BARRACUDA9000-3F',
                                                                                                     'BARRACUDA5500-1F',
                                                                                                     'KD122',
                                                                                                     'SE4500IE',
                                                                                                     'KS10000E-3',
                                                                                                     'S-THOR50IG',
                                                                                                     'ZBG3300C',
                                                                                                     'KS10000EG',
                                                                                                     'S-THOR10',
                                                                                                     'S-THOR10ATS',
                                                                                                     'S-THOR7',
                                                                                                     'F3001R',
                                                                                                     'ZBG10003CEA',
                                                                                                     '1.042-209.0'],
                                                                                                 'more': '',
                                                                                                 'name': 'AGREGAT PRADOTWÓRCZY 3KW, 230, BENZYNA, AVR'},
                                                                                             'KD122': {'quantity': '--',
                                                                                                       'price': '1359,93',
                                                                                                       'image': '',
                                                                                                       'kriterii': {},
                                                                                                       'alternative': [
                                                                                                           '3700.1',
                                                                                                           '3800.288',
                                                                                                           '3800.588',
                                                                                                           '3800.688',
                                                                                                           'KS 3000',
                                                                                                           'KS 7000E ATS',
                                                                                                           'KS 10000E',
                                                                                                           'EA3000N2 AVR',
                                                                                                           'KS10000E3',
                                                                                                           'KS3000E',
                                                                                                           'EP13500TE',
                                                                                                           'FH8000',
                                                                                                           'SE2000IE',
                                                                                                           'EA300N1',
                                                                                                           'FV13000TRE',
                                                                                                           'KS9200HDES1-3-ATSR',
                                                                                                           'KS8100HDE',
                                                                                                           'KS12-1E ATSR',
                                                                                                           'BARRACUDA9000-3F',
                                                                                                           'BARRACUDA5500-1F',
                                                                                                           'KD122',
                                                                                                           'SE4500IE',
                                                                                                           'KS10000E-3',
                                                                                                           'S-THOR50IG',
                                                                                                           'ZBG3300C',
                                                                                                           'KS10000EG',
                                                                                                           'S-THOR10',
                                                                                                           'S-THOR10ATS',
                                                                                                           'S-THOR7',
                                                                                                           'F3001R',
                                                                                                           'ZBG10003CEA',
                                                                                                           '1.042-209.0'],
                                                                                                       'more': '',
                                                                                                       'name': 'AGREGAT PRADOTWÓRCZY KD122 DIESEL 6,5KW AVR'},
                                                                                             'SMG-9T-K-AVR': {
                                                                                                 'quantity': '--',
                                                                                                 'price': '1478,46',
                                                                                                 'image': '',
                                                                                                 'kriterii': {},
                                                                                                 'alternative': [],
                                                                                                 'more': '',
                                                                                                 'name': 'AGREGAT PRADOTWÓRCZY 9KW, 230/400V, BENZYNA, AVR'},
                                                                                             'ZBG10003CEA': {
                                                                                                 'quantity': '--',
                                                                                                 'price': '2409,28',
                                                                                                 'image': 'C:\\Users\\user\\PycharmProjects\\intercars\\data\\0\\Diagnostic\\ZBG10003CEA\\logo.jpg',
                                                                                                 'kriterii': {
                                                                                                     'Käynnistinmoottori teho (kW)': '9 kW',
                                                                                                     'Polttoaine': 'Bensiini',
                                                                                                     'Jännite ulos [V]': '400 V'},
                                                                                                 'alternative': [
                                                                                                     '3700.1',
                                                                                                     '3800.288',
                                                                                                     '3800.588',
                                                                                                     '3800.688',
                                                                                                     'KS 3000',
                                                                                                     'KS 7000E ATS',
                                                                                                     'KS 10000E',
                                                                                                     'EA3000N2 AVR',
                                                                                                     'KS10000E3',
                                                                                                     'KS3000E',
                                                                                                     'EP13500TE',
                                                                                                     'FH8000',
                                                                                                     'SE2000IE',
                                                                                                     'EA300N1',
                                                                                                     'FV13000TRE',
                                                                                                     'KS9200HDES1-3-ATSR',
                                                                                                     'KS8100HDE',
                                                                                                     'KS12-1E ATSR',
                                                                                                     'BARRACUDA9000-3F',
                                                                                                     'BARRACUDA5500-1F',
                                                                                                     'KD122',
                                                                                                     'SE4500IE',
                                                                                                     'KS10000E-3',
                                                                                                     'S-THOR50IG',
                                                                                                     'ZBG3300C',
                                                                                                     'KS10000EG',
                                                                                                     'S-THOR10',
                                                                                                     'S-THOR10ATS',
                                                                                                     'S-THOR7',
                                                                                                     'F3001R',
                                                                                                     'ZBG10003CEA',
                                                                                                     '1.042-209.0'],
                                                                                                 'more': '',
                                                                                                 'name': 'AGREGAT PRADOTWÓRCZY 9,2KW, 230/400V, BENZYNA, AVR'},
                                                                                             'ZBG3300C': {
                                                                                                 'quantity': '--',
                                                                                                 'price': '637,08',
                                                                                                 'image': 'C:\\Users\\user\\PycharmProjects\\intercars\\data\\0\\Diagnostic\\ZBG3300C\\logo.jpg',
                                                                                                 'kriterii': {},
                                                                                                 'alternative': [
                                                                                                     '3700.1',
                                                                                                     '3800.288',
                                                                                                     '3800.588',
                                                                                                     '3800.688',
                                                                                                     'KS 3000',
                                                                                                     'KS 7000E ATS',
                                                                                                     'KS 10000E',
                                                                                                     'EA3000N2 AVR',
                                                                                                     'KS10000E3',
                                                                                                     'KS3000E',
                                                                                                     'EP13500TE',
                                                                                                     'FH8000',
                                                                                                     'SE2000IE',
                                                                                                     'EA300N1',
                                                                                                     'FV13000TRE',
                                                                                                     'KS9200HDES1-3-ATSR',
                                                                                                     'KS8100HDE',
                                                                                                     'KS12-1E ATSR',
                                                                                                     'BARRACUDA9000-3F',
                                                                                                     'BARRACUDA5500-1F',
                                                                                                     'KD122',
                                                                                                     'SE4500IE',
                                                                                                     'KS10000E-3',
                                                                                                     'S-THOR50IG',
                                                                                                     'ZBG3300C',
                                                                                                     'KS10000EG',
                                                                                                     'S-THOR10',
                                                                                                     'S-THOR10ATS',
                                                                                                     'S-THOR7',
                                                                                                     'F3001R',
                                                                                                     'ZBG10003CEA',
                                                                                                     '1.042-209.0'],
                                                                                                 'more': '',
                                                                                                 'name': 'AGREGAT PRADOTWÓRCZY 230V, 3KW, BENZYNA, AVR'}},
                                                                                         'Kärcher': {'1.042-209.0': {
                                                                                             'quantity': '--',
                                                                                             'price': '1389,14',
                                                                                             'image': 'C:\\Users\\user\\PycharmProjects\\intercars\\data\\0\\Kärcher\\10422090\\logo.jpg',
                                                                                             'kriterii': {
                                                                                                 'Käynnistinmoottori teho (kW)': '7,5 kW',
                                                                                                 'Polttoaine': 'Bensiini',
                                                                                                 'Jännite ulos [V]': '400 V'},
                                                                                             'alternative': ['3700.1',
                                                                                                             '3800.288',
                                                                                                             '3800.588',
                                                                                                             '3800.688',
                                                                                                             'KS 3000',
                                                                                                             'KS 7000E ATS',
                                                                                                             'KS 10000E',
                                                                                                             'EA3000N2 AVR',
                                                                                                             'KS10000E3',
                                                                                                             'KS3000E',
                                                                                                             'EP13500TE',
                                                                                                             'FH8000',
                                                                                                             'SE2000IE',
                                                                                                             'EA300N1',
                                                                                                             'FV13000TRE',
                                                                                                             'KS9200HDES1-3-ATSR',
                                                                                                             'KS8100HDE',
                                                                                                             'KS12-1E ATSR',
                                                                                                             'BARRACUDA9000-3F',
                                                                                                             'BARRACUDA5500-1F',
                                                                                                             'KD122',
                                                                                                             'SE4500IE',
                                                                                                             'KS10000E-3',
                                                                                                             'S-THOR50IG',
                                                                                                             'ZBG3300C',
                                                                                                             'KS10000EG',
                                                                                                             'S-THOR10',
                                                                                                             'S-THOR10ATS',
                                                                                                             'S-THOR7',
                                                                                                             'F3001R',
                                                                                                             'ZBG10003CEA',
                                                                                                             '1.042-209.0'],
                                                                                             'more': '',
                                                                                             'name': 'KARCHER AGREGAT PRADOTWÓRCZY 230/400V 7,5 KW AVR BENZYNA'}},
                                                                                         'ASTA': {'S-THOR10': {
                                                                                             'quantity': '--',
                                                                                             'price': '2682,30',
                                                                                             'image': 'C:\\Users\\user\\PycharmProjects\\intercars\\data\\0\\ASTA\\STHOR10\\logo.jpg',
                                                                                             'kriterii': {
                                                                                                 'Polttoaine': 'Diesel',
                                                                                                 'Käynnistinmoottori teho (kW)': '10 kW',
                                                                                                 'Jännite ulos [V]': '400 V'},
                                                                                             'alternative': ['3700.1',
                                                                                                             '3800.288',
                                                                                                             '3800.588',
                                                                                                             '3800.688',
                                                                                                             'KS 3000',
                                                                                                             'KS 7000E ATS',
                                                                                                             'KS 10000E',
                                                                                                             'EA3000N2 AVR',
                                                                                                             'KS10000E3',
                                                                                                             'KS3000E',
                                                                                                             'EP13500TE',
                                                                                                             'FH8000',
                                                                                                             'SE2000IE',
                                                                                                             'EA300N1',
                                                                                                             'FV13000TRE',
                                                                                                             'KS9200HDES1-3-ATSR',
                                                                                                             'KS8100HDE',
                                                                                                             'KS12-1E ATSR',
                                                                                                             'BARRACUDA9000-3F',
                                                                                                             'BARRACUDA5500-1F',
                                                                                                             'KD122',
                                                                                                             'SE4500IE',
                                                                                                             'KS10000E-3',
                                                                                                             'S-THOR50IG',
                                                                                                             'ZBG3300C',
                                                                                                             'KS10000EG',
                                                                                                             'S-THOR10',
                                                                                                             'S-THOR10ATS',
                                                                                                             'S-THOR7',
                                                                                                             'F3001R',
                                                                                                             'ZBG10003CEA',
                                                                                                             '1.042-209.0'],
                                                                                             'more': '',
                                                                                             'name': 'AGREGAT PRADOTWÓRCZY 10KW, 230/400V, DIESEL, AVR'},
                                                                                                  'S-THOR10ATS': {
                                                                                                      'quantity': '--',
                                                                                                      'price': '2842,00',
                                                                                                      'image': 'C:\\Users\\user\\PycharmProjects\\intercars\\data\\0\\ASTA\\STHOR10ATS\\logo.jpg',
                                                                                                      'kriterii': {
                                                                                                          'Polttoaine': 'Diesel',
                                                                                                          'Käynnistinmoottori teho (kW)': '10 kW',
                                                                                                          'Jännite ulos [V]': '400 V'},
                                                                                                      'alternative': [
                                                                                                          '3700.1',
                                                                                                          '3800.288',
                                                                                                          '3800.588',
                                                                                                          '3800.688',
                                                                                                          'KS 3000',
                                                                                                          'KS 7000E ATS',
                                                                                                          'KS 10000E',
                                                                                                          'EA3000N2 AVR',
                                                                                                          'KS10000E3',
                                                                                                          'KS3000E',
                                                                                                          'EP13500TE',
                                                                                                          'FH8000',
                                                                                                          'SE2000IE',
                                                                                                          'EA300N1',
                                                                                                          'FV13000TRE',
                                                                                                          'KS9200HDES1-3-ATSR',
                                                                                                          'KS8100HDE',
                                                                                                          'KS12-1E ATSR',
                                                                                                          'BARRACUDA9000-3F',
                                                                                                          'BARRACUDA5500-1F',
                                                                                                          'KD122',
                                                                                                          'SE4500IE',
                                                                                                          'KS10000E-3',
                                                                                                          'S-THOR50IG',
                                                                                                          'ZBG3300C',
                                                                                                          'KS10000EG',
                                                                                                          'S-THOR10',
                                                                                                          'S-THOR10ATS',
                                                                                                          'S-THOR7',
                                                                                                          'F3001R',
                                                                                                          'ZBG10003CEA',
                                                                                                          '1.042-209.0'],
                                                                                                      'more': '',
                                                                                                      'name': 'AGREGAT PRADOTWÓRCZY 10KW, 230/400V, DIESEL, AVR, ATS'},
                                                                                                  'S-THOR50IG': {
                                                                                                      'quantity': '--',
                                                                                                      'price': '610,25',
                                                                                                      'image': 'C:\\Users\\user\\PycharmProjects\\intercars\\data\\0\\ASTA\\STHOR50IG\\logo.jpg',
                                                                                                      'kriterii': {
                                                                                                          'Polttoaine': 'Bensiini',
                                                                                                          'Käynnistinmoottori teho (kW)': '5 kW',
                                                                                                          'Jännite ulos [V]': '230 V'},
                                                                                                      'alternative': [
                                                                                                          '3700.1',
                                                                                                          '3800.288',
                                                                                                          '3800.588',
                                                                                                          '3800.688',
                                                                                                          'KS 3000',
                                                                                                          'KS 7000E ATS',
                                                                                                          'KS 10000E',
                                                                                                          'EA3000N2 AVR',
                                                                                                          'KS10000E3',
                                                                                                          'KS3000E',
                                                                                                          'EP13500TE',
                                                                                                          'FH8000',
                                                                                                          'SE2000IE',
                                                                                                          'EA300N1',
                                                                                                          'FV13000TRE',
                                                                                                          'KS9200HDES1-3-ATSR',
                                                                                                          'KS8100HDE',
                                                                                                          'KS12-1E ATSR',
                                                                                                          'BARRACUDA9000-3F',
                                                                                                          'BARRACUDA5500-1F',
                                                                                                          'KD122',
                                                                                                          'SE4500IE',
                                                                                                          'KS10000E-3',
                                                                                                          'S-THOR50IG',
                                                                                                          'ZBG3300C',
                                                                                                          'KS10000EG',
                                                                                                          'S-THOR10',
                                                                                                          'S-THOR10ATS',
                                                                                                          'S-THOR7',
                                                                                                          'F3001R',
                                                                                                          'ZBG10003CEA',
                                                                                                          '1.042-209.0'],
                                                                                                      'more': '',
                                                                                                      'name': 'AGREGAT PRADOTWÓRCZY, INWERTER, 5KW, 230V'},
                                                                                                  'S-THOR7': {
                                                                                                      'quantity': '--',
                                                                                                      'price': '1049,14',
                                                                                                      'image': 'C:\\Users\\user\\PycharmProjects\\intercars\\data\\0\\ASTA\\STHOR7\\logo.jpg',
                                                                                                      'kriterii': {
                                                                                                          'Polttoaine': 'Bensiini',
                                                                                                          'Käynnistinmoottori teho (kW)': '7,5 kW',
                                                                                                          'Jännite ulos [V]': '400 V'},
                                                                                                      'alternative': [
                                                                                                          '3700.1',
                                                                                                          '3800.288',
                                                                                                          '3800.588',
                                                                                                          '3800.688',
                                                                                                          'KS 3000',
                                                                                                          'KS 7000E ATS',
                                                                                                          'KS 10000E',
                                                                                                          'EA3000N2 AVR',
                                                                                                          'KS10000E3',
                                                                                                          'KS3000E',
                                                                                                          'EP13500TE',
                                                                                                          'FH8000',
                                                                                                          'SE2000IE',
                                                                                                          'EA300N1',
                                                                                                          'FV13000TRE',
                                                                                                          'KS9200HDES1-3-ATSR',
                                                                                                          'KS8100HDE',
                                                                                                          'KS12-1E ATSR',
                                                                                                          'BARRACUDA9000-3F',
                                                                                                          'BARRACUDA5500-1F',
                                                                                                          'KD122',
                                                                                                          'SE4500IE',
                                                                                                          'KS10000E-3',
                                                                                                          'S-THOR50IG',
                                                                                                          'ZBG3300C',
                                                                                                          'KS10000EG',
                                                                                                          'S-THOR10',
                                                                                                          'S-THOR10ATS',
                                                                                                          'S-THOR7',
                                                                                                          'F3001R',
                                                                                                          'ZBG10003CEA',
                                                                                                          '1.042-209.0'],
                                                                                                      'more': '',
                                                                                                      'name': 'AGREGAT PRADOTWÓRCZY 7,5KW, 230/400V, BENZYNA, AVR'}}}}}}
